
spring.datasource.url=jdbc:postgresql://localhost:5432/SimpleDB
spring.datasource.username=postgres
spring.datasource.password=251098

spring.datasource.hikari.schema=public

server.port=8080
spring.application.name=simpledb-api
server.error.include-message=always
server.error.include-binding-errors=always